import { Component, OnInit, HostListener } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { IonicModule } from '@ionic/angular';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-game-cards',
  templateUrl: './game-cards.component.html',
  styleUrls: ['./game-cards.component.scss'],
  imports: [IonicModule, CommonModule],
})
export class GameCardsComponent implements OnInit {
  gameId!: number;
  cards: string[] = []; // To hold the selected game's card texts
  currentCardIndex = 0;
  cardImage: string = ''; // To hold the selected game's card image
  gameTitle: string = ''; // To hold the selected game's title
  fontSize = 14;

  // Define the card questions for each game based on gameId
  gameCardQuestions: { [key: number]: string[] } = {
    1: [
      "When is the first time you felt truly loved?",
      "Pizza or burger?",
      "Tea or coffee?",
      "What makes you feel beautiful?",
      "Ice cream or cookies?",
      "If you could return an item you bought years ago what would you return?",
      "What's your guilty pleasure?",
      "If you could change anything about your childhood, what would it be?",
      "What's something you did, that you instantly regretted?",
      "What's one thing you're afraid to tell anyone?",
      "Which decision do you think has had the biggest impact on your life?",
      "What is a fear you've never talked about?",
      "What do you need most when you're feeling stressed?",
      "How do you feel loved the most?",
      "What is your biggest regret?",
      "What's something you're passionate about that most people don't know?",
      "What's your favourite photo that you're in?",
      "What's your favorite way to unwind after a long day?",
      "If you could have dinner with anyone in the world, who would it be?",
      "How do vou define love?",
      "What situation did you completely misunderstand?",
      "What's something you've always wanted to try but haven't yet?",
      "What's a lesson you learned from a past relationship?",
      "What did you want to be when you grow up?",
      "What's the best advice you've ever given someone?",
      "You mean the world to this person. Who came to mind?",
      "What's one thing that guarantees a good date for you?",
      "Have you ever accidentally revealed a secret? If so how did it happen?",
      "If you slided into someone's DMs, what's the first thing you would text?",
      "What's the best gift you've ever received?",
      "How would you tell a friend something you know she doesn't want to hear?",
      "What qualities do you value most in a friendship?",
      "How would you tell a friend something you know he/she doesn't want to hear?",
      "Who do vou look up to, and why?",
      "Have you ever broken up with a friend, and why? How did you do it?",
      "What's one thing you did that was wrong, but you're not sorry about?",
      "What steps have you taken recently for your personal growth and self-improvement?",
      "If a genie gave you three wishes, what would they be?",
      "How do you envision your dream life?",
      "What goal are you working toward right now?",
      "What is on your bucket list?",
      "What life lessons have you had to learn the hard way?",
      "If you could change one historic event, which one would it be?",
      "What does happiness mean to you?",
      "High paying job, or freedom as an entrepreneur?",
      "Which hobbies have you always wanted to try?",
      "How do you define success?",
      "What's an essential part of your daily routine?",
      "If you could only watch one movie over and over for the rest of vour life. which movie would you choose?",
      "Which movie have you watched more than twice?",
      "If you could only eat one food for the rest of your life, what would it be?",
      "What was the best vacation you ever took ?",
      "What values are fundamental to you and why?",
      "Which song makes you cry every time?",
      "Which song would you like to listen to right now?",
      "Where would you like to live when you're ninety years old?",
      "What's your favourite song right now?",
      "What's one romantic relationship you're most sad ended? Why did it end?",
      "What's your favorite way to spend a day off?",
      "Why her? Why him?",
      "Why not him? Why not her?",
      "Which luxury do you believe should be a human right?",
      "What's something about you that will never change?",
      "Answer a question of your choice.",
      "What's one thing you know is true for sure?",
      "What values do vou live by?",
      "What's one life hack you've figured out for yourself?",
      "You're stuck on an island other than your phone, what's something you always have in your bag that would be useful?",
      "If you could choose your nationality and ethnicity, which ones would you choose?",
      "What's one foreign tradition you wish would become law?",
      "What is vour favourite word?",
      "You receive a deliverv of 1.000 kilos of one vegetable. You can't return it. Which vegetable do you wish it is?",
      "What's something you owe your parents an apology for?",
      "What's something that makes someone instantly attractive, to you?",
      "What's something you still need to forgive your parents for?",
      "What draws people to you?",
      "Without naming them, tell us about someone you're absolutely attracted to, but are not in a relationship with.",
      "What's something you just hate, or cannot stand?",
      "If you could double one sense. but you had to lose one sense in exchange, which one would you double, which one would you lose?",
      "What's the most expensive mistake you ever made?",
      "What's the cheapest thing you've ever bought that you use everyday?",
      "What's the biggest mistake you ever made at work?",
      "What's the one thing you ever paid the most amount of cash for?",
      "What's your go-to lie when you need to get out of any plans?",
      "Provide more details for one of the questions you already answered.",
      "What's one thing you were blamed for but you really didn't do?",
      "Pick one person to answer this question: What's one thing you wish I would change?",
      "There's been a crime: You have to frame one family member in order to save one family member. Who would vou frame and who would you save?",
      "Pick one person in the room, and tell them one thing you really admire about them.",
      "If someone offered to finance a business for you and take all the risks, what business would you start?",
      "If you could live in any era, past or future. which era would you choose?",
      "Would you marry yourself?",
      "What's one thing that is legal, that you think shouldn't be?",
      "If someone made a movie about you, which scene would you like them to start with?",
      "If someone you love were to come back to life, what's the first thing you would update them on?",
      "What's the biggest financial mistake you ve ever made?",
      "What's the best financial decision you've ever made?",
      "When was the last time you cried?",
      "Of all the things you've ever lost, which one do you wish you could get back?",
      "What do you think about when you need to feel safe?",
      "When is the last time you laughed the most?",
      "Where do you feel most at home?",
      "Where is your safe place?",
      "What's one dream you've given up on?",
      "Who is one person from your childhood, who impacted you the most. but has no idea they did?",
      "What's a movie that has had a significant impact on you?",
      "What's one thing you've said in the past, that you wish you could go back and say differently?",
      "If someone wanted to make you feel special, what would they need to do?",
      "What's the most spontaneous thing you've done recently?",
      "How do you define happiness?",
      "Which historical event shocks you the most?",
      "What does success mean to you?", 
      "Who is one person you were wrong about?",
      "What's one virtue/value you won't compromise?",
      "What's a mistake you've made that taught you a valuable lesson?",
      "How did you know your last relationship was over?",
      "What's the best piece of advice you've received about relationships?",
      "What's your love language?",
      "Ask anyone a follow-up question.",
      "How do you show affection?",
      "Who has been the most influential person in your life?",
      "What did you want to be when you grow up, and how do you feel about that now?",
      "What qualities do you value most in a partner?",
      "What's a skill you've always wanted to learn?",  
      "What's one useless skill you have?",
      "If money were no object, what would you do with your time?",
      "If you could achieve only one thing in your life, what would you want it to be?",
      "What's the best advice you ve ever received?",
      "What's something you wish your parents had taught you?",
      "How do you handle major decisions?",
      "What's the most significant lesson you learned from your parents?",
      "What's one thing you're proud of that might surprise people?",
      "Have vou ever been in an emergency situation? How did you respond?",
      "If vou had to call someone who you are 100% sure will answer, who would you call?",
      "Arrested. Who is your one phone call?",
      "If you had to go undercover, which occupation would you choose?",
      "What's something that recently made you cry?",
      "When is the last time you felt really loved?",
      "What is something that people often misunderstand about you?",
      "What is something that no one knows about you?",
      "Which of your childhood experiences has had the biggest impact on you?",
      "What's your favourite quality about yourself?",
      "If you could live anywhere in the world, where would you live?",
      "Who is somebody you feel you owe an apology?",
      "What is the most hurtful thing someone has ever said to you?",
      "How has your parent's relationship affected how you view relationships?",
      "You're in jail... What did you do to get yourself there?",
      "If you could make one item illegal, which item would you choose?",
      "What's one day you wish you could go back to, and do things differently?",
      "If you could make one virtue into law. which virtue would you choose?",  
      "If you could freeze one day in your past and make it loop forever, which day would you choose?",
      "What makes you feel beautiful?",
      "If you could go on a date with your childhood crush, where would you go?",
      "What's the best decision you've ever made?",
      "What makes you feel alive?",
      "How has parenthood changed you?",
      "If you could have dinner with anyone, dead or alive, who would you choose?",
      "What something you always thought you were right about, that you now realize were wrong about?",
      "If you could be someone else for 24 hours. who would you choose?",
      "When was a moment you felt really understood?",
      "Who is someone you underestimated at first?",
      "When was a moment you felt reallv alone?",
      "If whole world was listening, what would you say?",
      "Ask the next person any question",
      "When is the last time you had to be brave?",
      "Answer the previous question",
      "When is the last time you felt afraid?",
      "What's a question you wish people would ask you more often?",
      "What's one trend you wish would stop to exist?",
      "What's one quality you like in your parents, that you see in yourself?",
      "You're stuck on an island, other than your phone, what's one thing you always have in your bag that would be useful?",
      "What's one quality you dislike in your parents that you see in yourself?",
      "If you could undo one political decision in past history, which one would you undo?",
      "Describe your perfect date.",
      "What's the best date you ever been on?",
      "You get dropped into the biggest mall in the world. You have more money than you've ever had before. What would you buy?",
      "What's the first thing you notice about a person?",
      "What's something you wish your parents would just talk to you about?",
      "You're on a blind date, you realise the person is a wanted fugitive, what do you do next?",
      "You won the Nobel Peace Prize, what did you do to win it?",  
      "Watching your parents raise you, how did that impact your decision to have or not have kids?",
      "If you could apologise to your younger self, what would you apologise for?",
      "Where do you see yourself living five years from now?",
      "What childhood memory makes you laugh?",
      "What's one thing you find challenging about your partner/spouse?",
      "What childhood memory makes you sad?",
      "What drives you to get up every morning?",
      "What do you value most in a friend?",
      "What is your personal brand?",
      "Who is somebody you've lost contact with that you wish you could reconnect with?",
      "What values are fundamental to you and why?",
      "What fear have you overcome?",
      "What's the bravest thing that you have ever done?",
      "What's the most intense/overwhelming crush you've ever had?",
      "If you could have lunch with anyone tomorrow, whom would you choose?",
      "You have to disappear. Where do you go?",
      "What's one memory that still makes you cry?",
      "What experience has challenged you the most?",
      "How old would you be if you didn't know how old you are?", 
      "What's something you've dreamed of doing for a long time?",
      "What would you do differently if the average human lifespan were only 40 years?",
      "If you had to live without one of your five senses. which one would you choose?",
      "If you could read minds for one hour, whose mind would you choose to read?",
      "If today were your last day on Earth, how would you spend it?",
      "What's one piece of advice you would give to your younger self?",
      "You've been appointed Principal of your high school. Which rules do you keep, which ones do you get rid of?",
      "What is your biggest hope for the future?",
      "Is there someone you wish you could tell how you truly feel?",
      "If you could go back and change the course of your life, which age would you go back to, and what would you do differently?",
      "Imagine that you found out you were adopted. What things would suddenly make sense to you?",
      "If you could make one item illegal, which item would you choose?",
      "What is the most hurtful thing someone has ever said to you?",
      "What is your personal brand?",
      "You're in jail... What did you do to get yourself there?",
      "Who is somebody you feel you owe an apology?",
      "What's one day you wish you could go back to, and do things differently?",
      "How has your parent's relationship affected how you view relationships?",
      "If you could go on a date with your childhood crush, where would you go?",
      "If you could make one virtue into law, which virtue would you choose?",
      "What makes you feel alive?",
      "If you could freeze one day in your past and make it loop forever, which day would you choose?",
      "How do you deal with rejection?",
      "When is a moment you felt really sure of yourself?",
      "What's something you never want to do again?",
      "When is a moment you felt really unsure of yourself?",
      "What's one country vou've visited that you wish you never visit again?",
      "What's something you definitely want to do again?",
      "What item do you believe should be more expensive than it is right now?",
      "What item do you believe should be cheaper than it is right now?",
      "Make a wish on behalf of a sibling.",
      "Make a wish on behalf of your children.",
      "Make a wish on behalf of your boss.",
      "Make a wish on behalf of your parents.",
      "What changed your opinion about love?",
      "You move to a foreign country where you do know anyone. What's the first thing you would do in order to make friends?",
      "What's something you wish you didn't know?",
      "What's something you wish you knew then that you know now?",
      "Have you found your talent yet? If yes, what is it?",
      "What's something you wish you never found out?",
      "What has been your most humbling experience?",
      "What's the most difficult thing you've ever done?",
      "What's the strangest thing that has ever happened to you?",
      "What's one moment in your life you will never forget?",
      "What do you think is the most valuable skill in life?",
      "What moment in your life did you feel most beautiful?",
      "Weekends: stay in or go out?",
      "What's one conspiracy theory you definitely believe?",
      "Tomorrow you wake up in a different continent You don't remember the flight. What's the most likely explanation for how you got there?",
      "Describe yourself in three words.",
      "What's one thing you could never live without?",
      "What's one thing you compromise on, even though you hold a completely different opinion?",
      "Your partner goes missing where's the first place you'd look?",
      "Your partner is working offshore for one month. What's the one thing that will be a complete mess by the time he/she returns?",
      "What's the biggest difference between how you grew up and how you live today?",
      "What do you bring to the table?",
      "What are some things that your parents did, that you will definitely not do while raising your kids?",
      "What's something you get wrong, all the time?",
      "What are some things that your parents were right about?",
      "You have to choose between being rich or being beautiful. What do you choose?",
      "What's the best compliment you ever received from a stranger?",
    ],
    5: [
      "What was your childhood like?",
      "What's your family dynamic?",
      "What are your favorite childhood memories?",
      "Who has been the most influential person in your life?",
      "What are some traditions your family has?",
      "What does a healthy relationship look like to you?",
      "How do you feel about public displays of affection?",
      "What are your thoughts on marriage?",
      "How do you handle conflicts in a relationship?",
      "What are your expectations from a partner?",
      "Where do you see yourself in five years?",
      "What are your career goals?",
      "Do you want to have children someday? If so, how many?",
      "What's your idea of a perfect life together?",
      "How important is travel to you?",
      "What's your favorite way to spend a weekend?",
      "Do you have any hobbies you're passionate about?",
      "What's the last book you read that you loved?",
      "What kind of music do you enjoy, and why?",
      "Do you prefer staying in or going out for fun?",
      "If you could have dinner with any three people, dead or alive, who would they be?",
      "What's the most embarrassing thing that ever happened to you?",
      "If you could instantly learn one skill, what would it be?",
      "What's your guilty pleasure TV show or movie?",
      "If you could travel anywhere in the world right now, where would it be?",
      "What values are most important to you in life?",
      "How do you define success?",
      "Do you believe in fate or free will? Why?",
      "How do you feel about spirituality or religion?",
      "What causes or issues are you passionate about?",
      "What's your idea of a perfect date night?",
      "How do you express love and affection?",
      "What's something romantic that someone has done for you that really touched you?",
      "How do you feel about surprise gifts or gestures?",
      "What's one thing that always makes you smile?",
      "How do you prefer to communicate when upset?",
      "Are there any topics that make you uncomfortable discussing?",
      "How can I best support you during tough times?",
      "Do you prefer texting or talking on the phone for important conversations?",
      "How often do you think couples should check in with each other emotionally?",
      "Are you a morning person or a night owl?",
      "How do you feel about pets? Do you want any in the future?",
      "What's your approach to health and fitness?",
      "How do you manage stress or unwind after a long day?",
      "What's your favorite way to relax?",
      "How do we handle disagreements as a couple?",
      "What's one thing I can do to make our relationship stronger?",
      "How do we ensure we maintain our individual identities while being together?",
      "What is something new we can try together as a couple?",
      "How can we celebrate our successes together?",
      "What does intimacy mean to you beyond physical connection?",
      "How important is sexual compatibility in a relationship for you?",
      "Are there any boundaries you'd like to discuss regarding intimacy?",
      "What's your love language, and how do I show it effectively for you?",        
      "How do we keep the spark alive over time?",
      "When did you first realize you liked me?",
      "What's something you've learned about yourself since we started dating?",
      "How have past relationships shaped what you're looking for now?",
      "What's one thing about me that surprised you when we started dating?",
      "Do you think we have compatible lifestyles?",
      "How do we want to handle finances as a couple in the future?",
      "Would we ever want to live together? If so, where would that be?",
      "What are your thoughts on co-parenting if we have children?",
      "How often should we plan vacations together?",
      "Are there any major life changes you're anticipating soon?",
      "What's one thing you've always wanted to ask me but haven't yet?",
      "If there was one thing you'd change about our relationship, what would it be?",
      "What's a dream you've had that you'd like to share with me?",
      "In what ways can we better support each other during stressful times?",
      "What's something you'd like us to accomplish together this year?",
      "If money were no object, what would be your dream vacation?",
      "If we could live anywhere in the world, where would it be and why?",
      "Would you rather have superhuman strength or the ability to fly?",
      "If we could time travel, which era would you want to visit together?",
      "If animals could talk, which one would be the most interesting?",
      "What's your favorite food combination that most people find weird?",
      "Do you prefer coffee or tea, and how do you take it?",
      "What's your favorite season and why?",
      "Are there any foods you're absolutely allergic to or dislike?",
      "What's one dish you'd love for me to cook for you?",
      "How has our relationship changed since we first met?",
      "What's your favorite memory of us so far?",
      "Is there anything you've wanted to try together but haven't yet?",
      "When was the moment you knew I was someone special to you?",
      "Do our friends and family see us as a good match?",
    ],
    4: [
      "Tell me about yourself.",
      "What are your hobbies?",
      "How would your coworkers describe you?",
      "What motivates you?",
      "What are your strengths?",
      "What are your weaknesses?",
      "How do you handle stress or pressure?",
      "Describe your work ethic.",
      "What is your greatest accomplishment?",
      "Where do you see yourself in 5 years?",
      "Why do you want this job?",
      "Why should we hire you?",
      "What do you know about our company?",
      "What can you bring to the company?",
      "What challenges are you looking for in this position?",
      "What would you do in the first month in the job?",
      "What is your ideal work environment?",
      "What's your management style?",
      "How do you prioritize tasks?",
      "How do you stay organized?",
      "Why is there a gap in your work history?",
      "Why did you leave your last job?",
      "What experience do you have in this field?",
      "What skills do you have that are relevant to this position?",
      "Can you describe a time you demonstrated leadership?",
      "How do you handle difficult coworkers?",
      "Tell me about a time you made a mistake at work.",
      "How do you handle criticism?",
      "Describe a situation where you had to work as part of a team.",
      "How do you approach problem-solving?",
      "What are your career goals?",
      "How does this position align with your career goals?",
      "What type of work environment do you prefer?",
      "Are you willing to travel for work?",
      "Are you open to relocating?",
      "What are your salary expectations?",
      "How do you plan to achieve your career goals?",
      "What do you hope to learn in this position?",
      "Where do you see yourself in 10 years?",
      "How do you stay current in your field?",
      "Describe a time when you had to meet a tight deadline.",
      "Tell me about a time you had to deal with a difficult customer.",
      "How have you handled conflict with a supervisor?",
      "Describe a situation where you had to think on your feet.",
      "Tell me about a time you went above and beyond at work.",
      "How do you handle working under pressure?",
      "Describe a time when you had to adapt to a significant change at work.",
      "Tell me about a time you failed and how you handled it.",
      "How do you handle multiple competing priorities?",
      "Describe a situation where you had to motivate others.",
      "What do you know about our products/services?",
      "Who are our main competitors?",
      "What do you think sets us apart from our competitors?",
      "What do you think are the biggest challenges facing our industry?",
      "How do you see our company evolving in the next 5 years?",
      "How would you handle an upset customer?",
      "What would you do if you disagreed with a coworker's approach to a project?",
      "How would you react if given an impossible deadline?",
      "What would you do if you caught a coworker stealing?",
      "How would you handle a situation where you were asked to do something unethical?",
      "How do you ensure clear communication in a team?",
      "Describe a time when you had to explain a complex concept to someone.",
      "How do you tailor your communication style for different audiences?",
      "Tell me about a time when miscommunication led to a problem at work.",
      "How do you handle giving constructive feedback?",
      "Describe a time when you took initiative on a project.",
      "How do you motivate team members?",
      "Tell me about a time you had to make a difficult decision.",
      "How do you delegate tasks effectively?",
      "Describe a situation where you had to lead a team through a challenging project.",
      "Describe a complex problem you solved at work.",
      "How do you approach decision-making?",
      "Tell me about a time you had to think creatively to solve a problem.",
      "How do you gather and analyze information to make decisions?",
      "Describe a situation where you had to use data to support a recommendation.",
      "How do you manage your time effectively?",
      "Describe your approach to meeting deadlines.",
      "How do you handle multiple projects simultaneously?",
      "Tell me about a time when you had to reprioritize your workload.",
      "How do you ensure you don't forget important tasks or deadlines?",
      "Describe a time when you had to learn a new skill quickly.",
      "How do you handle unexpected changes to your work plans?",
      "Tell me about a time you had to work outside your comfort zone.",
      "How do you stay flexible in a fast-paced work environment?",
      "Describe a situation where you had to adapt to a new team or work culture.",
      "How do you define excellent customer service?",
      "Describe a time when you turned an unhappy customer into a satisfied one.",
      "How do you handle customer complaints?",
      "Tell me about a time you went above and beyond for a customer.",
      "How do you balance customer satisfaction with company policies?",
      "How do you contribute to a positive team environment?",
      "Describe a time when you had to work with a difficult team member.",
      "How do you handle differences of opinion within a team?",
      "Tell me about a successful team project you were part of.",
      "How do you ensure effective communication in a team setting?",
      "How do you maintain a healthy work-life balance?",
      "How do you handle work-related stress?",
      "Are you comfortable with occasional overtime or weekend work?",
      "How do you recharge outside of work?",
      "How do you prioritize your personal and professional life?",
      "What software or tools are you proficient in?",
      "How do you stay updated with new technologies in your field?",
      "Describe a time when you had to learn a new software quickly.",
      "How comfortable are you with remote work tools?",
      "What's your approach to learning new technologies?",
      "Describe a time when you faced an ethical dilemma at work.",
      "How do you ensure confidentiality in your work?",
      "What does professional integrity mean to you?",
      "How would you handle a situation where you witnessed unethical behavior?",
      "Describe a time when you had to stand up for what you believed was right.",
      "How do you foster creativity in your work?",
      "Describe a time when you came up with an innovative solution.",
      "How do you generate new ideas?",
      "Tell me about a time you challenged the status quo at work.",
      "How do you stay inspired and motivated in your work?",
      "Describe your approach to conflict resolution.",
      "Tell me about a time you successfully mediated a conflict.",
      "How do you handle disagreements with supervisors?",
      "Describe a situation where you had to give difficult feedback.",
      "How do you maintain professionalism during conflicts?",
      "What type of company culture do you thrive in?",
      "How do you contribute to a positive work environment?",
      "Describe your ideal coworker.",
      "How do you handle workplace diversity?",
      "What values are most important to you in a workplace?",
      "How do you stay current in your field?",
      "What professional development activities do you engage in?",
      "Where do you see your career progressing?",
      "What skills would you like to develop further?",
      "How do you set and achieve professional goals?",
      "How do you stay productive when working remotely?",
      "What challenges have you faced with remote work?",
      "How do you maintain team connections in a remote setting?",
      "What tools do you use for remote collaboration?",
      "How do you ensure work-life balance when working from home?",
      "What industry trends are you following?",
      "How do you think our industry will evolve in the next few years?",
      "What challenges do you think our industry faces?",
      "Who do you consider thought leaders in our field?",
      "How do you stay informed about industry news and developments?",
      "Describe your approach to project management.",
      "How do you handle project setbacks or delays?",
      "Tell me about a successful project you managed.",
      "How do you ensure projects stay on budget and on schedule?",
      "How do you manage stakeholder expectations in a project?",
      "How do you build professional relationships?",
      "Describe your approach to networking.",
      "How do you maintain professional connections?",
      "Tell me about a time when networking led to a professional opportunity.",
      "How do you leverage your professional network in your work?",
      "How do you approach self-improvement?",
      "Describe a time when you identified and improved an inefficient process.",
      "How do you solicit and act on feedback?",
      "What steps do you take to continuously improve your skills?",
      "How do you encourage continuous improvement in a team setting?",
      "Describe a time when you faced a significant setback at work.",
      "How do you stay motivated during long-term projects?",
      "Tell me about a time you had to persevere through a difficult situation.",
      "How do you maintain a positive attitude in challenging times?",
      "Describe a situation where your resilience was tested.",
      "Describe your decision-making process.",
      "Tell me about a difficult decision you had to make at work.",
      "How do you make decisions when you don't have all the information?",
      "Describe a time when you had to make an unpopular decision.",
      "How do you involve others in the decision-making process?",
      "How do you set and track goals?",
      "Describe a significant goal you achieved and how you did it.",
      "How do you align your personal goals with organizational goals?",
      "What do you do when you're not meeting your goals?",
      "How do you celebrate achieving your goals?",
      "How do you perform under pressure?",
      "Describe a high-pressure situation you handled well.",
      "What techniques do you use to manage stress?",
      "How do you maintain focus during stressful periods?",
      "Tell me about a time when you had to meet a challenging deadline.",
      "Describe a significant failure in your career and what you learned.",
      "How do you handle professional disappointments?",
      "What's your approach to learning from mistakes?",
      "Tell me about a time when failure led to a valuable lesson.",
      "How do you encourage a culture that views failure as a learning opportunity?",
      "How would you describe your personal brand?",
      "What unique value do you bring to a team or organization?",
      "How do you maintain your professional reputation?",
      "What do you want to be known for in your career?",
      "How do you differentiate yourself from others in your field?",
      "Are you more comfortable working independently or as part of a team?",
      "How do you handle repetitive tasks?",
      "Describe your ideal work environment.",
      "How do you approach multitasking?",
      "What's your preferred method of communication at work?"
    ],
    3: [
      "Are there any family traditions from your childhood that you'd like us to continue or adapt for our family?",
      "Are there any fantasies you'd like to explore together?",
      "Describe your ideal lazy Sunday.",
      "Do you feel more emotionally connected now than at the beginning of our relationship?",
      "How can I better speak your love language?",
      "How can I make you feel seen and accepted during intimacy?",
      "How can we achieve emotional intimacy together?",
      "How can we better support each other in our individual goals?",
      "How can we bring more laughter into our daily lives?",
      "How can we encourage each other's personal growth?",
      "How can we improve our communication with each other?",
      "How can we maintain a healthy work-life balance while prioritizing our relationship?",
      "How can we prioritize intimacy in our relationship?",
      "How do you envision a day in the life of us with kids (if applicable)?",
      "How do you express your emotions, and how can I support that?",
      "How do you feel about the current state of our relationship?",
      "How do you feel loved and appreciated in our relationship?",
      "How do you feel when we spend time apart from each other?",
      "How do you handle feelings of jealousy or insecurity?",
      "How do you plan to save for retirement, and what are your goals?",
      "How do you prefer to handle conflicts or disagreements?",
      "How do your values shape your actions?",
      "How often would you like us to have date nights?",
      "If I could give you three wishes for our future, what would they be?",
      "If money didn't matter, what would you want to do together?",
      "If we could have any pet in the world, what would it be?",
      "If we could renew our vows, what would be important for us to include?",
      "If we could travel anywhere together, where would it be and why?",
      "If we had a couple's handshake, what would it look like?",
      "If you could change one thing about where we live, what would it be?",
      "If you could relive one special moment from our past, which one would it be?",
      "Is there anything you'd change about our relationship?",
      "Share a moment from our relationship that made you laugh the hardest.",
      "What activities do you enjoy doing with me the most?",
      "What activities or hobbies should we explore together?",
      "What are some fond memories from our dating days?",
      "What are some unresolved issues from our past that we should address?",
      "What are your biggest fears?",
      "What are your biggest strengths?",
      "What are your biggest weaknesses?",
      "What are your expectations of me as a partner?",
      "What are your hopes and dreams for our future together?",
      "What aspect of my nature do you find most awe-inspiring?",
      "What boundaries are most important to you in our relationship?",
      "What brings you the most pleasure during intimate moments?",
      "What can we do to strengthen our bond?",
      "What do you appreciate most about our relationship?",
      "What does emotional intimacy mean to you?",
      "What makes you feel secure in our relationship?",
      "What new traditions can we create to make our relationship special?",
      "What shared goals do you want us to work on as a couple?",
      "What values are most important to you?",
      "What was your first impression of me when we met?",
      "What would a perfect date-night look like to you?",
      "What's a piece of advice you've ever given someone about their relationship that worked out?",
      "What's one thing that drains you in relationships, and how can I help alleviate that?",
      "What's something about your intimate history you've never shared before?",
      "What's something I can do outside of the bedroom to keep intimacy alive throughout the day?",
      "What's something new you'd like us to try as a couple?",
      "What's something you've always wanted to learn?",
      "What's something you've always wanted to try together?",
      "What's something you've never told anyone else before that you'd like to share with me?",
      "What's the best advice you've ever received about relationships?",
      "What's the funniest thing you've said in your sleep?",
      "What's the most spontaneous thing we've ever done together?",
      "What's your favorite memory of us together?",
      "What's your guilty pleasure that you'd like to share with me?",
      "What's your love language?",
      "When did you know you wanted to be in a serious relationship with me?",
      "Where do you see us in five years?",
      "Would you like me to be more or less assertive in the bedroom?"
    ],
    9: [
      "Tell us briefly about yourself.",
  "Why do you want to become a cabin crew member?",
  "What are your best qualities that might be useful as a cabin crew member?",
  "Why do you want to work for our airline?",
  "How did you hear about this position?",
  "Describe a time you went above and beyond to provide great customer service.",
  "How do you handle difficult passengers?",
  "Can you give an example of a time when you resolved a problem with an angry customer?",
  "How do you ensure passenger safety during emergency landings?",
  "How do you maintain professionalism while interacting with passengers?",
  "Describe a time you argued with a coworker.",
  "What would you do if your coworker refused to follow a new policy?",
  "You’ve noticed a coworker or passenger violating safety standards. How would you respond?",
  "Describe a time you resolved a crisis at work.",
  "How would you deal with being away from your family and friends for long periods of time?",
  "Describe a time when you worked successfully as part of a team.",
  "What would you do if a coworker was not doing their share of the work?",
  "How do you handle teamwork in stressful situations?",
  "Can you provide an example of how you've contributed to team success in the past?",
  "What role do you usually take in group settings?",
  "Describe a time you suggested an improvement to a work process.",
  "How do you handle unexpected situations during flights?",
  "Can you describe an instance where your quick thinking prevented a problem from escalating?",
  "What steps do you take to adapt to changes in procedures or schedules?",
  "How do you prioritize tasks when faced with multiple demands?",
  "How do you ensure clear communication with passengers who speak different languages?",
  "Can you give an example of how you've effectively communicated in a challenging situation?",
  "How would you explain safety procedures to passengers who are not paying attention?",
  "Describe how you'd handle miscommunication between crew members.",
  "What techniques do you use to ensure passengers understand important announcements?",
  "Would you be ready to jump out of a plane in case of an emergency?",
  "How would you handle an emergency on board?",
  "Describe your approach to managing panic among passengers during emergencies.",
  "What training have you received that prepares you for emergency situations?",
  "How do you stay calm under pressure during emergencies?",
  "What are your strengths and weaknesses as they relate to this role?",
  "How do you manage stress and maintain composure during long flights?",
  "Describe your approach to maintaining personal health and fitness for this job.",
  "What motivates you in your career as cabin crew?",
  "How do your personal values align with the airline's mission?",
  "What are the key responsibilities of cabin crew members?",
  "How does the role of cabin crew contribute to the airline's success?",
  "What challenges do cabin crew face, and how would you address them?",
  "Why is passenger safety so important, and how can it be ensured at all times?",
  "What trends in the aviation industry impact the role of cabin crew?",
  "How would you handle cultural differences among passengers or crew members?",
  "Can you provide an example of how you've respected cultural diversity in the past?",
  "Why is cultural sensitivity important in international flights?",
  "Describe how you'd manage language barriers with passengers.",
  "What steps would you take to ensure all passengers feel valued and respected?",
  "How do you handle repetitive tasks?",
  "Describe a time when you had to learn a new skill quickly.",
  "How do you handle unexpected changes to your work plans?",
  "Tell me about a time you had to work outside your comfort zone.",
  "How do you stay flexible in a fast-paced work environment?",
  "Describe a situation where you had to adapt to a new team or work culture.",
  "How do you define excellent customer service?",
  "Describe a time when you turned an unhappy customer into a satisfied one.",
  "How do you handle customer complaints?",
  "Tell me about a time you went above and beyond for a customer.",
  "How do you balance customer satisfaction with company policies?",
  "How do you contribute to a positive team environment?",
  "Describe a time when you had to work with a difficult team member.",
  "How do you handle differences of opinion within a team?",
  "How do you handle work-related stress?",
  "Describe a time when you faced an ethical dilemma at work.",
  "How do you ensure confidentiality in your work?",
  "What does professional integrity mean to you?",
  "How would you handle a situation where you witnessed unethical behavior?",
  "Describe a time when you had to stand up for what you believed was right.",
  "Describe your approach to conflict resolution.",
  "How do you contribute to a positive work environment?",
  "How do you handle workplace diversity?",
  "How do you think our industry will evolve in the next few years?",
  "How do you solicit and act on feedback?",
  "Describe a situation where your resilience was tested.",
  "Tell me about a difficult decision you had to make at work.",
  "How do you make decisions when you don't have all the information?",
  "How do you perform under pressure?",
  "How do you maintain focus during stressful periods?"
    ],
  };

  // Map game IDs to their corresponding card image
  gameCardImages: { [key: number]: string } = {
    1: 'assets/images/cards-game1.png',
    5: 'assets/images/cards-game5.png',
    4: 'assets/images/cards-game4.png',
    3: 'assets/images/cards-game3.png',
    9: 'assets/images/cards-game9.png',
  };

  // Map game IDs to their corresponding titles
  games: { id: number; name: string; image: string }[] = [
    { id: 1, name: 'Dare to Connect Games', image: 'assets/images/game1.png' },
    { id: 5, name: 'Talking Stage', image: 'assets/images/game5.png' },
    { id: 4, name: 'Job Interview', image: 'assets/images/game4.png' },
    { id: 3, name: 'Couples Therapy', image: 'assets/images/game3.png' },
    { id: 9, name: 'Cabin Crew Interview Questions', image: 'assets/images/game9.png' },
  ];

  constructor(private route: ActivatedRoute, private router: Router) {}

  ngOnInit() {
    // Get game ID from the URL
    
    this.gameId = Number(this.route.snapshot.paramMap.get('id'));

    // Load the correct card questions and image for the game based on the game ID
    this.cards = this.gameCardQuestions[this.gameId] || []; // Fallback to empty array if no match
    this.cardImage = this.gameCardImages[this.gameId] || ''; // Fallback to empty string if no match

    // Get the game's title by matching the gameId
    const game = this.games.find(game => game.id === this.gameId);
    if (game) {
      this.gameTitle = game.name;
    }

    // Check for saved card progress in localStorage
    const savedCardIndex = localStorage.getItem(`game-${this.gameId}-progress`);
    if (savedCardIndex) {
      this.currentCardIndex = Number(savedCardIndex);
    }
    this.adjustFontSize();
  }

  // Navigate to the next card
  nextCard() {
    if (this.currentCardIndex < this.cards.length - 1) {
      this.currentCardIndex++;
      this.adjustFontSize();
      this.saveProgress();
    }
  }

  // Navigate to the previous card
  previousCard() {
    if (this.currentCardIndex > 0) {
      this.currentCardIndex--;
      this.adjustFontSize();
      this.saveProgress();
    }
  }

  // Save current progress in localStorage
  saveProgress() {
    localStorage.setItem(`game-${this.gameId}-progress`, String(this.currentCardIndex));
  }

  adjustFontSize() {
    const maxChars = 40; // Maximum characters before reducing font size
    const baseFontSize = 14; // Default font size
    const minFontSize = 11; // Minimum font size for readability

    // Adjust the font size dynamically based on the current card's text length
    const currentTextLength = this.cards[this.currentCardIndex]?.length || 0;
    if (currentTextLength > maxChars) {
      const reductionFactor = Math.floor((currentTextLength - maxChars) / 10);
      this.fontSize = Math.max(baseFontSize - reductionFactor, minFontSize);
    } else {
      this.fontSize = baseFontSize;
    }
  }
}
